### ISSUE TITLE
bug: 404 on dynamic routes

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/sample-next-app#106]
Inspecting the https://sample-next-app.fabrique.social.gouv.fr one can see strange 404 request..

![image](https://user-images.githubusercontent.com/730511/72739842-cb514e00-3ba4-11ea-9bb9-0c4defdf8814.png)

**Comment by revolunet** [comment]
I guess this is the preloading of invalid pages. page3 and page-error are two examples supposed to trigger a sentry event

**Comment by douglasduteil** [comment]
[AFK discussion]
