### ISSUE TITLE
[discuss] backend

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/sample-next-app#111]
ATM this repo only host the frontend code (http UI + API)

To have a full stack application we need to add a backend. This could be done in several ways: direct PG connection, via an intermediate custom API, or via Hasura.

Lets imagine with an hasura backend : We'd need to add 3 generic components to the app :

 - jwt-api : node-api with PG connection for account and JWT management
 - [hasura](https://github.com/hasura/graphql-engine) : GraphQL API with PG
 - Postgres : could be internal or external

These 3 components finally just serve the purpose of a "backend as a service"

Ideally :
 - dev should be able to trigger hasura commands from the pipeline (ex: migrate)
 - frontend updates should not redeploy backends if not necessary
 - the only code related to these components should be the hasura migrations 

Would be cool to have @nkrmr @kwiss input here :)

**Comment by nkrmr** [comment]
Here related links about this subject

https://blog.hasura.io/best-practices-of-using-jwt-with-graphql/
https://blog.hasura.io/add-authentication-and-authorization-to-next-js-8-serverless-apps-using-jwt-and-graphql/

**Comment by revolunet** [comment]
And.... i 💛 the serverless topic popping here :)

**Comment by revolunet** [comment]
Also, two potential ways to distribute this service :

 - include the code/containers... in your app
 - use the backend "as a service"

**Comment by revolunet** [comment]
check #135
