### ISSUE TITLE
improv: 12factor checking

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/sample-next-app#51]
https://12factor.net/fr/

**Comment by revolunet** [comment]
# 12 facteurs

 - [ ] Base de code : Une base de code suivie avec un système de contrôle de version, plusieurs déploiements
 - [ ] Dépendances : Déclarez explicitement et isolez les dépendances
 - [ ] Configuration : Stockez la configuration dans l’environnement
 - [ ] Services externes : Traitez les services externes comme des ressources attachées
 - [ ] Build, release, run : Séparez strictement les étapes d’assemblage et d’exécution
 - [ ] Processus : Exécutez l’application comme un ou plusieurs processus sans état
 - [ ] Associations de ports : Exportez les services via des associations de ports
 - [ ] Concurrence : Grossissez à l’aide du modèle de processus
 - [ ] Jetable : Maximisez la robustesse avec des démarrages rapides et des arrêts gracieux
 - [ ] Parité dev/prod : Gardez le développement, la validation et la production aussi proches que possible
 - [ ] Logs : Traitez les logs comme des flux d’évènements
 - [ ] Processus d’administration : Lancez les processus d’administration et de maintenance comme des one-off-processes
